# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boolean.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1415, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadbutton = QtWidgets.QPushButton(self.centralwidget)
        self.loadbutton.setGeometry(QtCore.QRect(310, 460, 151, 51))
        self.loadbutton.setObjectName("loadbutton")
        self.citralabel = QtWidgets.QLabel(self.centralwidget)
        self.citralabel.setGeometry(QtCore.QRect(80, 20, 640, 360))
        self.citralabel.setFrameShape(QtCore.Qt.QFrame::Shape::Box)
        self.citralabel.setText("")
        self.citralabel.setObjectName("citralabel")
        self.citralabel2 = QtWidgets.QLabel(self.centralwidget)
        self.citralabel2.setGeometry(QtCore.QRect(740, 20, 640, 360))
        self.citralabel2.setFrameShape(QtCore.Qt.QFrame::Shape::Box)
        self.citralabel2.setText("")
        self.citralabel2.setObjectName("citralabel2")
        self.loadbutton2 = QtWidgets.QPushButton(self.centralwidget)
        self.loadbutton2.setGeometry(QtCore.QRect(990, 460, 152, 51))
        self.loadbutton2.setObjectName("loadbutton2")
        self.aritmethicButton = QtWidgets.QPushButton(self.centralwidget)
        self.aritmethicButton.setGeometry(QtCore.QRect(310, 550, 151, 51))
        self.aritmethicButton.setObjectName("aritmethicButton")
        self.aritmethicButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.aritmethicButton_2.setGeometry(QtCore.QRect(490, 550, 151, 51))
        self.aritmethicButton_2.setObjectName("aritmethicButton_2")
        self.aritmethicButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.aritmethicButton_3.setGeometry(QtCore.QRect(660, 550, 151, 51))
        self.aritmethicButton_3.setObjectName("aritmethicButton_3")
        self.aritmethicButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.aritmethicButton_4.setGeometry(QtCore.QRect(840, 550, 151, 51))
        self.aritmethicButton_4.setObjectName("aritmethicButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1415, 24))
        self.menubar.setObjectName("menubar")
        self.menuoperasi_titik = QtWidgets.QMenu(self.menubar)
        self.menuoperasi_titik.setToolTipsVisible(True)
        self.menuoperasi_titik.setObjectName("menuoperasi_titik")
        self.menurotasi = QtWidgets.QMenu(self.menubar)
        self.menurotasi.setObjectName("menurotasi")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMin45_Degree = QtWidgets.QAction(MainWindow)
        self.actionMin45_Degree.setObjectName("actionMin45_Degree")
        self.action45_Degree = QtWidgets.QAction(MainWindow)
        self.action45_Degree.setObjectName("action45_Degree")
        self.actionMin90_Degree = QtWidgets.QAction(MainWindow)
        self.actionMin90_Degree.setObjectName("actionMin90_Degree")
        self.action90_Degree = QtWidgets.QAction(MainWindow)
        self.action90_Degree.setObjectName("action90_Degree")
        self.action180_Degree = QtWidgets.QAction(MainWindow)
        self.action180_Degree.setObjectName("action180_Degree")
        self.menuoperasi_titik.addAction(self.actionMin45_Degree)
        self.menuoperasi_titik.addAction(self.action45_Degree)
        self.menuoperasi_titik.addAction(self.actionMin90_Degree)
        self.menuoperasi_titik.addAction(self.action90_Degree)
        self.menuoperasi_titik.addAction(self.action180_Degree)
        self.menubar.addAction(self.menuoperasi_titik.menuAction())
        self.menubar.addAction(self.menurotasi.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadbutton.setText(_translate("MainWindow", "Load Image"))
        self.loadbutton2.setText(_translate("MainWindow", "Load Image 2"))
        self.aritmethicButton.setText(_translate("MainWindow", "and"))
        self.aritmethicButton_2.setText(_translate("MainWindow", "or"))
        self.aritmethicButton_3.setText(_translate("MainWindow", "xor"))
        self.aritmethicButton_4.setText(_translate("MainWindow", "not"))
        self.menuoperasi_titik.setTitle(_translate("MainWindow", "Rotasi"))
        self.menurotasi.setTitle(_translate("MainWindow", "rotasi"))
        self.actionMin45_Degree.setText(_translate("MainWindow", "-45 Degree"))
        self.action45_Degree.setText(_translate("MainWindow", "45 Degree"))
        self.actionMin90_Degree.setText(_translate("MainWindow", "-90 Degree"))
        self.action90_Degree.setText(_translate("MainWindow", "90 Degree"))
        self.action180_Degree.setText(_translate("MainWindow", "180 Degree"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
